services:
  - type: web
    name: project-management-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_USER
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: EXPIRY_TIME
        value: "1h"
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: FRONTEND_URL
        sync: false
